FSINET:
  GENDER_NUM_EMBED: 2
  GENDER_EMBED_DIM: 1
  AGE_NUM_EMBED: 6
  AGE_EMBED_DIM: 2
  BODY_SHAPE_NUM_EMBED: 6
  BODY_SHAPE_EMBED_DIM: 2
  ATTACHMENT_NUM_EMBED: 11
  ATTACHMENT_EMBED_DIM: 5
  UPPER_BODY_CLOTHING_NUM_EMBED: 25
  UPPER_BODY_CLOTHING_EMBED_DIM: 3
  LOWER_BODY_CLOTHING_NUM_EMBED: 23
  LOWER_BODY_CLOTHING_EMBED_DIM: 2
  EMBED_FC1_OUT: 256
  EMBED_FC2_OUT: 512
  RESNET_FC1_OUT: 1024
  RESNET_FC2_OUT: 512
  FC1_OUT: 512
  FC2_OUT: 256
  CKPT: "deep_sort/deep/checkpoint/fsinet_checkpoint.pth"
